# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k325tffg900-2
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property ip_repo_paths /home/sanjayr/projects/KC705/PCIe_gen2x8_PIO_test13/vivado_IP_GEN [current_fileset]

read_ip /home/sanjayr/projects/KC705/PCIe_gen2x8_PIO_test13/IP/pcie_7x_gen2x8_core_example/pcie_7x_gen2x8_core_example.srcs/sources_1/ip/pcie_7x_gen2x8_core/pcie_7x_gen2x8_core.xci
set_property used_in_implementation false [get_files -all /home/sanjayr/projects/KC705/PCIe_gen2x8_PIO_test13/IP/pcie_7x_gen2x8_core_example/pcie_7x_gen2x8_core_example.srcs/sources_1/ip/pcie_7x_gen2x8_core/pcie_7x_gen2x8_core/source/pcie_7x_gen2x8_core-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all /home/sanjayr/projects/KC705/PCIe_gen2x8_PIO_test13/IP/pcie_7x_gen2x8_core_example/pcie_7x_gen2x8_core_example.srcs/sources_1/ip/pcie_7x_gen2x8_core/synth/pcie_7x_gen2x8_core_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files /home/sanjayr/projects/KC705/PCIe_gen2x8_PIO_test13/IP/pcie_7x_gen2x8_core_example/pcie_7x_gen2x8_core_example.srcs/sources_1/ip/pcie_7x_gen2x8_core/pcie_7x_gen2x8_core.xci]

read_verilog {
  /home/sanjayr/projects/KC705/PCIe_gen2x8_PIO_test13/IP/pcie_7x_gen2x8_core_example/pcie_7x_gen2x8_core_example.srcs/sources_1/imports/example_design/EP_MEM.v
  /home/sanjayr/projects/KC705/PCIe_gen2x8_PIO_test13/IP/pcie_7x_gen2x8_core_example/pcie_7x_gen2x8_core_example.srcs/sources_1/imports/example_design/PIO_TX_ENGINE.v
  /home/sanjayr/projects/KC705/PCIe_gen2x8_PIO_test13/IP/pcie_7x_gen2x8_core_example/pcie_7x_gen2x8_core_example.srcs/sources_1/imports/example_design/PIO_RX_ENGINE.v
  /home/sanjayr/projects/KC705/PCIe_gen2x8_PIO_test13/IP/pcie_7x_gen2x8_core_example/pcie_7x_gen2x8_core_example.srcs/sources_1/imports/example_design/PIO_EP_MEM_ACCESS.v
  /home/sanjayr/projects/KC705/PCIe_gen2x8_PIO_test13/IP/pcie_7x_gen2x8_core_example/pcie_7x_gen2x8_core_example.srcs/sources_1/imports/example_design/PIO_TO_CTRL.v
  /home/sanjayr/projects/KC705/PCIe_gen2x8_PIO_test13/IP/pcie_7x_gen2x8_core_example/pcie_7x_gen2x8_core_example.srcs/sources_1/imports/example_design/PIO_EP.v
  /home/sanjayr/projects/KC705/PCIe_gen2x8_PIO_test13/IP/pcie_7x_gen2x8_core_example/pcie_7x_gen2x8_core_example.srcs/sources_1/imports/example_design/PIO.v
  /home/sanjayr/projects/KC705/PCIe_gen2x8_PIO_test13/IP/pcie_7x_gen2x8_core_example/pcie_7x_gen2x8_core_example.srcs/sources_1/imports/example_design/pcie_app_7x.v
  /home/sanjayr/projects/KC705/PCIe_gen2x8_PIO_test13/IP/pcie_7x_gen2x8_core_example/pcie_7x_gen2x8_core_example.srcs/sources_1/imports/example_design/xilinx_pcie_2_1_ep_7x.v
}
read_xdc /home/sanjayr/projects/KC705/PCIe_gen2x8_PIO_test13/IP/pcie_7x_gen2x8_core_example/pcie_7x_gen2x8_core_example.srcs/constrs_1/imports/example_design/xilinx_pcie_7x_ep_x8g2_KC705_REVC.xdc
set_property used_in_implementation false [get_files /home/sanjayr/projects/KC705/PCIe_gen2x8_PIO_test13/IP/pcie_7x_gen2x8_core_example/pcie_7x_gen2x8_core_example.srcs/constrs_1/imports/example_design/xilinx_pcie_7x_ep_x8g2_KC705_REVC.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/sanjayr/projects/KC705/PCIe_gen2x8_PIO_test13/IP/pcie_7x_gen2x8_core_example/pcie_7x_gen2x8_core_example.data/wt [current_project]
set_property parent.project_dir /home/sanjayr/projects/KC705/PCIe_gen2x8_PIO_test13/IP/pcie_7x_gen2x8_core_example [current_project]
synth_design -top xilinx_pcie_2_1_ep_7x -part xc7k325tffg900-2
write_checkpoint xilinx_pcie_2_1_ep_7x.dcp
report_utilization -file xilinx_pcie_2_1_ep_7x_utilization_synth.rpt -pb xilinx_pcie_2_1_ep_7x_utilization_synth.pb
