set_property SRC_FILE_INFO {cfile:/home/sanjayr/projects/boeing/IPI_demo/PCIE_AXI_BRIDGE/KINTEX_KC705/vivado_IPI_project_64bit_if/project_X/project_X.srcs/sources_1/bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_mig_7series_0_0/pcie_gen2x1_sub_sys_mig_7series_0_0/user_design/constraints/pcie_gen2x1_sub_sys_mig_7series_0_0.xdc rfile:../../../project_X.srcs/sources_1/bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_mig_7series_0_0/pcie_gen2x1_sub_sys_mig_7series_0_0/user_design/constraints/pcie_gen2x1_sub_sys_mig_7series_0_0.xdc id:1 order:EARLY scoped_inst:pcie_gen2x1_sub_sys_i/mig_7series_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/sanjayr/projects/boeing/IPI_demo/PCIE_AXI_BRIDGE/KINTEX_KC705/vivado_IPI_project_64bit_if/project_X/project_X.srcs/sources_1/bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_pcie_7x_0_0/source/pcie_gen2x1_sub_sys_pcie_7x_0_0-PCIE_X0Y0.xdc rfile:../../../project_X.srcs/sources_1/bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_pcie_7x_0_0/source/pcie_gen2x1_sub_sys_pcie_7x_0_0-PCIE_X0Y0.xdc id:2 order:EARLY scoped_inst:pcie_gen2x1_sub_sys_i/pcie_7x_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/sanjayr/projects/boeing/IPI_demo/PCIE_AXI_BRIDGE/KINTEX_KC705/vivado_IPI_project_64bit_if/pcie_gen2x1_sub_sys_wrapper.xdc rfile:../../../../pcie_gen2x1_sub_sys_wrapper.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:/home/sanjayr/projects/boeing/IPI_demo/PCIE_AXI_BRIDGE/KINTEX_KC705/vivado_IPI_project_64bit_if/project_X/project_X.srcs/sources_1/bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_cc_0/pcie_gen2x1_sub_sys_auto_cc_0_clocks.xdc rfile:../../../project_X.srcs/sources_1/bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_cc_0/pcie_gen2x1_sub_sys_auto_cc_0_clocks.xdc id:4 order:LATE scoped_inst:pcie_gen2x1_sub_sys_i/axi_interconnect_0/m00_couplers/auto_cc/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/sanjayr/projects/boeing/IPI_demo/PCIE_AXI_BRIDGE/KINTEX_KC705/vivado_IPI_project_64bit_if/project_X/project_X.srcs/sources_1/bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_cc_1/pcie_gen2x1_sub_sys_auto_cc_1_clocks.xdc rfile:../../../project_X.srcs/sources_1/bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_cc_1/pcie_gen2x1_sub_sys_auto_cc_1_clocks.xdc id:5 order:LATE scoped_inst:pcie_gen2x1_sub_sys_i/axi_interconnect_0/m01_couplers/auto_cc/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/sanjayr/projects/boeing/IPI_demo/PCIE_AXI_BRIDGE/KINTEX_KC705/vivado_IPI_project_64bit_if/project_X/project_X.srcs/sources_1/bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_cc_2/pcie_gen2x1_sub_sys_auto_cc_2_clocks.xdc rfile:../../../project_X.srcs/sources_1/bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_cc_2/pcie_gen2x1_sub_sys_auto_cc_2_clocks.xdc id:6 order:LATE scoped_inst:pcie_gen2x1_sub_sys_i/axi_interconnect_0/m02_couplers/auto_cc/inst} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:732 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y3 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:733 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:734 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:735 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y0 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:736 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:737 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:738 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:739 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y11 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:740 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y10 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:741 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y9 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:742 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y8 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:744 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y3 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:745 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:746 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:747 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y0 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:751 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y11 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:752 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y10 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:753 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y9 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:754 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y8 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:758 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y3 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:759 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:760 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:761 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y0 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:762 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:763 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:764 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:765 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y11 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:766 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y10 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:767 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y9 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:768 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y8 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:770 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y3 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:771 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:772 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:773 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y0 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:774 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y11 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:775 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y10 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:776 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y9 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:777 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y8 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:779 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y0 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:1 line:780 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:1 line:781 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:1 line:783 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y0 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:1 line:784 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:1 line:785 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:1 line:787 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y43 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:788 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y31 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:789 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y19 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:790 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:791 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y143 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:792 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y131 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:793 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y119 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:794 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y107 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:796 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PLLE2_ADV_X1Y1 [get_cells -hier -filter {NAME =~ */u_ddr3_infrastructure/plle2_i}]
set_property src_info {type:SCOPED_XDC file:1 line:797 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC MMCME2_ADV_X1Y1 [get_cells -hier -filter {NAME =~ */u_ddr3_infrastructure/gen_mmcm.mmcm_i}]
set_property src_info {type:SCOPED_XDC file:1 line:815 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/* && IS_SEQUENTIAL}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1*}] 20
set_property src_info {type:SCOPED_XDC file:1 line:816 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hier *rstdiv0_sync_r1_reg*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] -datapath_only 5
set_property src_info {type:SCOPED_XDC file:1 line:818 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *ddr3_infrastructure/rstdiv0_sync_r1_reg*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/xadc_supplied_temperature.rst_r1*}] 20
set_property src_info {type:SCOPED_XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X0Y7 [get_cells {inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property src_info {type:SCOPED_XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PCIE_X0Y0 [get_cells inst/pcie_top_i/pcie_7x_i/pcie_block_i]
set_property src_info {type:SCOPED_XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X5Y35 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[3].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X4Y36 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[2].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X4Y35 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[1].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X4Y34 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[0].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X4Y33 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[0].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X4Y32 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[1].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X4Y31 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[2].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X4Y30 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[3].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:XDC file:3 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X0Y1 [get_cells refclk_ibuf]
set_property src_info {type:XDC file:3 line:9 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 labtools_ila_v3
set_property src_info {type:XDC file:3 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:3 line:19 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list pcie_gen2x1_sub_sys_i/pcie_7x_0_user_clk_out]]
set_property src_info {type:XDC file:3 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WSTRB[0]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WSTRB[1]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WSTRB[2]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WSTRB[3]}]]
set_property src_info {type:XDC file:3 line:22 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:3 line:24 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[0]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[1]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[2]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[3]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[4]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[5]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[6]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[7]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[8]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[9]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[10]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[11]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[12]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[13]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[14]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[15]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[16]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[17]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[18]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[19]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[20]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[21]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[22]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[23]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[24]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[25]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[26]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[27]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[28]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[29]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[30]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WDATA[31]}]]
set_property src_info {type:XDC file:3 line:25 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:3 line:27 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RRESP[0]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RRESP[1]}]]
set_property src_info {type:XDC file:3 line:28 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:3 line:30 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[0]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[1]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[2]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[3]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[4]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[5]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[6]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[7]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[8]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[9]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[10]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[11]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[12]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[13]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[14]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[15]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[16]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[17]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[18]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[19]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[20]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[21]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[22]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[23]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[24]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[25]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[26]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[27]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[28]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[29]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[30]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[31]}]]
set_property src_info {type:XDC file:3 line:31 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:3 line:33 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[0]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[1]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[2]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[3]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[4]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[5]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[6]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[7]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[8]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[9]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[10]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[11]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[12]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[13]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[14]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[15]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[16]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[17]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[18]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[19]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[20]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[21]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[22]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[23]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[24]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[25]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[26]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[27]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[28]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[29]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[30]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[31]}]]
set_property src_info {type:XDC file:3 line:34 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:3 line:36 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[0]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[1]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[2]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[3]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[4]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[5]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[6]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[7]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[8]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[9]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[10]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[11]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[12]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[13]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[14]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[15]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[16]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[17]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[18]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[19]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[20]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[21]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[22]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[23]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[24]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[25]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[26]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[27]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[28]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[29]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[30]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RDATA[31]}]]
set_property src_info {type:XDC file:3 line:37 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:3 line:39 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_BRESP[0]} {pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_BRESP[1]}]]
set_property src_info {type:XDC file:3 line:40 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:3 line:42 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARESETN]]
set_property src_info {type:XDC file:3 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:3 line:45 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARREADY]]
set_property src_info {type:XDC file:3 line:46 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:3 line:48 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_ARVALID]]
set_property src_info {type:XDC file:3 line:49 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:3 line:51 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWREADY]]
set_property src_info {type:XDC file:3 line:52 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:3 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_AWVALID]]
set_property src_info {type:XDC file:3 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_BREADY]]
set_property src_info {type:XDC file:3 line:58 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:3 line:60 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_BVALID]]
set_property src_info {type:XDC file:3 line:61 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:3 line:63 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RREADY]]
set_property src_info {type:XDC file:3 line:64 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:3 line:66 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_RVALID]]
set_property src_info {type:XDC file:3 line:67 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:3 line:69 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WREADY]]
set_property src_info {type:XDC file:3 line:70 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:3 line:72 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list pcie_gen2x1_sub_sys_i/pcie_axi_brdg/inst/u_axiLite_debug/dbg_M_AXI_WVALID]]
set_property src_info {type:XDC file:3 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:SCOPED_XDC file:4 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_fanout -from [get_ports s_axi_aclk] -flat -endpoints_only] {IS_LEAF}] -to [filter [all_fanout -from [get_ports m_axi_aclk] -flat -only_cells] {IS_SEQUENTIAL && (NAME !~ *dout_i_reg[*])}] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins pcie_gen2x1_sub_sys_i/axi_interconnect_0/m00_couplers/auto_cc/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:4 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_fanout -from [get_ports m_axi_aclk] -flat -endpoints_only] {IS_LEAF}] -to [filter [all_fanout -from [get_ports s_axi_aclk] -flat -only_cells] {IS_SEQUENTIAL && (NAME !~ *dout_i_reg[*])}] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins pcie_gen2x1_sub_sys_i/axi_interconnect_0/m00_couplers/auto_cc/inst/m_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:4 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_disable_timing -from CLK -to O [filter [all_fanout -from [get_ports s_axi_aclk] -flat -endpoints_only -only_cells] {PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==LUTRAM}]
set_property src_info {type:SCOPED_XDC file:4 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_disable_timing -from CLK -to O [filter [all_fanout -from [get_ports m_axi_aclk] -flat -endpoints_only -only_cells] {PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==LUTRAM}]
set_property src_info {type:SCOPED_XDC file:5 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_fanout -from [get_ports s_axi_aclk] -flat -endpoints_only] {IS_LEAF}] -to [filter [all_fanout -from [get_ports m_axi_aclk] -flat -only_cells] {IS_SEQUENTIAL && (NAME !~ *dout_i_reg[*])}] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins pcie_gen2x1_sub_sys_i/axi_interconnect_0/m01_couplers/auto_cc/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:5 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_fanout -from [get_ports m_axi_aclk] -flat -endpoints_only] {IS_LEAF}] -to [filter [all_fanout -from [get_ports s_axi_aclk] -flat -only_cells] {IS_SEQUENTIAL && (NAME !~ *dout_i_reg[*])}] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins pcie_gen2x1_sub_sys_i/axi_interconnect_0/m01_couplers/auto_cc/inst/m_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:5 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_disable_timing -from CLK -to O [filter [all_fanout -from [get_ports s_axi_aclk] -flat -endpoints_only -only_cells] {PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==LUTRAM}]
set_property src_info {type:SCOPED_XDC file:5 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_disable_timing -from CLK -to O [filter [all_fanout -from [get_ports m_axi_aclk] -flat -endpoints_only -only_cells] {PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==LUTRAM}]
set_property src_info {type:SCOPED_XDC file:6 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_fanout -from [get_ports s_axi_aclk] -flat -endpoints_only] {IS_LEAF}] -to [filter [all_fanout -from [get_ports m_axi_aclk] -flat -only_cells] {IS_SEQUENTIAL && (NAME !~ *dout_i_reg[*])}] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins pcie_gen2x1_sub_sys_i/axi_interconnect_0/m02_couplers/auto_cc/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:6 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_fanout -from [get_ports m_axi_aclk] -flat -endpoints_only] {IS_LEAF}] -to [filter [all_fanout -from [get_ports s_axi_aclk] -flat -only_cells] {IS_SEQUENTIAL && (NAME !~ *dout_i_reg[*])}] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins pcie_gen2x1_sub_sys_i/axi_interconnect_0/m02_couplers/auto_cc/inst/m_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:6 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_disable_timing -from CLK -to O [filter [all_fanout -from [get_ports s_axi_aclk] -flat -endpoints_only -only_cells] {PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==LUTRAM}]
set_property src_info {type:SCOPED_XDC file:6 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_disable_timing -from CLK -to O [filter [all_fanout -from [get_ports m_axi_aclk] -flat -endpoints_only -only_cells] {PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==LUTRAM}]
