# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/sanjayr/projects/boeing/IPI_demo/PCIE_AXI_BRIDGE/KINTEX_KC705/vivado_IPI_project_64bit_if/pcie_gen2x1_sub_sys_wrapper.xdc

# Block Designs: bd/pcie_gen2x1_sub_sys/pcie_gen2x1_sub_sys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys || ORIG_REF_NAME==pcie_gen2x1_sub_sys}]

# IP: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_axi_bram_ctrl_0_0/pcie_gen2x1_sub_sys_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_axi_bram_ctrl_0_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_axi_bram_ctrl_0_0}]

# IP: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_axi_gpio_0_0/pcie_gen2x1_sub_sys_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_axi_gpio_0_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_axi_gpio_0_0}]

# IP: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_axi_interconnect_0_0/pcie_gen2x1_sub_sys_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_axi_interconnect_0_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_axi_interconnect_0_0}]

# IP: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_xbar_0/pcie_gen2x1_sub_sys_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_xbar_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_xbar_0}]

# IP: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_blk_mem_gen_0_0/pcie_gen2x1_sub_sys_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_blk_mem_gen_0_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_blk_mem_gen_0_0}]

# IP: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_mig_7series_0_0/pcie_gen2x1_sub_sys_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_mig_7series_0_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_mig_7series_0_0}]

# IP: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_pcie_7x_0_0/pcie_gen2x1_sub_sys_pcie_7x_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_pcie_7x_0_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_pcie_7x_0_0}]

# IP: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_pcie_axi_brdg_0/pcie_gen2x1_sub_sys_pcie_axi_brdg_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_pcie_axi_brdg_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_pcie_axi_brdg_0}]

# IP: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_rst_mig_7series_0_200M_0/pcie_gen2x1_sub_sys_rst_mig_7series_0_200M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_rst_mig_7series_0_200M_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_rst_mig_7series_0_200M_0}]

# IP: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_rst_pcie_sys_250M_0/pcie_gen2x1_sub_sys_rst_pcie_sys_250M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_rst_pcie_sys_250M_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_rst_pcie_sys_250M_0}]

# IP: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_pc_0/pcie_gen2x1_sub_sys_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_auto_pc_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_auto_pc_0}]

# IP: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_us_0/pcie_gen2x1_sub_sys_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_auto_us_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_auto_us_0}]

# IP: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_cc_0/pcie_gen2x1_sub_sys_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_auto_cc_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_auto_cc_0}]

# IP: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_cc_1/pcie_gen2x1_sub_sys_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_auto_cc_1 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_auto_cc_1}]

# IP: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_ds_0/pcie_gen2x1_sub_sys_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_auto_ds_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_auto_ds_0}]

# IP: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_cc_2/pcie_gen2x1_sub_sys_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_auto_cc_2 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_auto_cc_2}]

# IP: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_ds_1/pcie_gen2x1_sub_sys_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_auto_ds_1 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_auto_ds_1}]

# IP: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_pc_1/pcie_gen2x1_sub_sys_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_auto_pc_1 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_auto_pc_1}]

# IP: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_us_1/pcie_gen2x1_sub_sys_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_auto_us_1 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_auto_us_1}]

# IP: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_rs_0/pcie_gen2x1_sub_sys_auto_rs_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_auto_rs_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_auto_rs_0}]

# IP: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_rs_w_0/pcie_gen2x1_sub_sys_auto_rs_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_auto_rs_w_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_auto_rs_w_0}]

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_axi_bram_ctrl_0_0/pcie_gen2x1_sub_sys_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_axi_gpio_0_0/pcie_gen2x1_sub_sys_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_axi_gpio_0_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_axi_gpio_0_0/pcie_gen2x1_sub_sys_axi_gpio_0_0_ooc.xdc

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_axi_gpio_0_0/pcie_gen2x1_sub_sys_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_axi_gpio_0_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_xbar_0/pcie_gen2x1_sub_sys_xbar_0_ooc.xdc

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_blk_mem_gen_0_0/pcie_gen2x1_sub_sys_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_mig_7series_0_0/pcie_gen2x1_sub_sys_mig_7series_0_0/user_design/constraints/pcie_gen2x1_sub_sys_mig_7series_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_mig_7series_0_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_mig_7series_0_0}]

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_mig_7series_0_0/pcie_gen2x1_sub_sys_mig_7series_0_0/user_design/constraints/pcie_gen2x1_sub_sys_mig_7series_0_0_ooc.xdc

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_mig_7series_0_0/pcie_gen2x1_sub_sys_mig_7series_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_mig_7series_0_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_mig_7series_0_0}]

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_pcie_7x_0_0/source/pcie_gen2x1_sub_sys_pcie_7x_0_0-PCIE_X0Y0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_pcie_7x_0_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_pcie_7x_0_0}] {/inst }]/inst ]]

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_pcie_7x_0_0/synth/pcie_gen2x1_sub_sys_pcie_7x_0_0_ooc.xdc

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_rst_mig_7series_0_200M_0/pcie_gen2x1_sub_sys_rst_mig_7series_0_200M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_rst_mig_7series_0_200M_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_rst_mig_7series_0_200M_0}]

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_rst_mig_7series_0_200M_0/pcie_gen2x1_sub_sys_rst_mig_7series_0_200M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_rst_mig_7series_0_200M_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_rst_mig_7series_0_200M_0}]

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_rst_mig_7series_0_200M_0/pcie_gen2x1_sub_sys_rst_mig_7series_0_200M_0_ooc.xdc

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_rst_pcie_sys_250M_0/pcie_gen2x1_sub_sys_rst_pcie_sys_250M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_rst_pcie_sys_250M_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_rst_pcie_sys_250M_0}]

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_rst_pcie_sys_250M_0/pcie_gen2x1_sub_sys_rst_pcie_sys_250M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_rst_pcie_sys_250M_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_rst_pcie_sys_250M_0}]

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_rst_pcie_sys_250M_0/pcie_gen2x1_sub_sys_rst_pcie_sys_250M_0_ooc.xdc

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_pc_0/pcie_gen2x1_sub_sys_auto_pc_0_ooc.xdc

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_us_0/pcie_gen2x1_sub_sys_auto_us_0_ooc.xdc

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_us_0/pcie_gen2x1_sub_sys_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_auto_us_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_cc_0/pcie_gen2x1_sub_sys_auto_cc_0_ooc.xdc

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_cc_0/pcie_gen2x1_sub_sys_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_auto_cc_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_auto_cc_0}] {/inst }]/inst ]]

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_cc_1/pcie_gen2x1_sub_sys_auto_cc_1_ooc.xdc

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_cc_1/pcie_gen2x1_sub_sys_auto_cc_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_auto_cc_1 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_auto_cc_1}] {/inst }]/inst ]]

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_ds_0/pcie_gen2x1_sub_sys_auto_ds_0_ooc.xdc

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_ds_0/pcie_gen2x1_sub_sys_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_auto_ds_0 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_auto_ds_0}] {/inst }]/inst ]]

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_cc_2/pcie_gen2x1_sub_sys_auto_cc_2_ooc.xdc

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_cc_2/pcie_gen2x1_sub_sys_auto_cc_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_auto_cc_2 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_auto_cc_2}] {/inst }]/inst ]]

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_ds_1/pcie_gen2x1_sub_sys_auto_ds_1_ooc.xdc

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_ds_1/pcie_gen2x1_sub_sys_auto_ds_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_auto_ds_1 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_auto_ds_1}] {/inst }]/inst ]]

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_pc_1/pcie_gen2x1_sub_sys_auto_pc_1_ooc.xdc

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_us_1/pcie_gen2x1_sub_sys_auto_us_1_ooc.xdc

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_us_1/pcie_gen2x1_sub_sys_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen2x1_sub_sys_auto_us_1 || ORIG_REF_NAME==pcie_gen2x1_sub_sys_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_rs_0/pcie_gen2x1_sub_sys_auto_rs_0_ooc.xdc

# XDC: bd/pcie_gen2x1_sub_sys/ip/pcie_gen2x1_sub_sys_auto_rs_w_0/pcie_gen2x1_sub_sys_auto_rs_w_0_ooc.xdc

# XDC: bd/pcie_gen2x1_sub_sys/pcie_gen2x1_sub_sys_ooc.xdc
