set_property SRC_FILE_INFO {cfile:/home/sanjayr/projects/AC701/PCIe_gen2x8_PIO_test18/vivado_IPI_example_2/project_X/project_X.srcs/sources_1/bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_mig_7series_0_0/pcie_gen1x1_sub_sys_mig_7series_0_0/user_design/constraints/pcie_gen1x1_sub_sys_mig_7series_0_0.xdc rfile:../../../project_X.srcs/sources_1/bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_mig_7series_0_0/pcie_gen1x1_sub_sys_mig_7series_0_0/user_design/constraints/pcie_gen1x1_sub_sys_mig_7series_0_0.xdc id:1 order:EARLY scoped_inst:pcie_gen1x1_sub_sys_i/mig_7series_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/sanjayr/projects/AC701/PCIe_gen2x8_PIO_test18/vivado_IPI_example_2/project_X/project_X.srcs/sources_1/bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_pcie_7x_0_0/pcie_gen1x1_sub_sys_pcie_7x_0_0/source/pcie_gen1x1_sub_sys_pcie_7x_0_0-PCIE_X0Y0.xdc rfile:../../../project_X.srcs/sources_1/bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_pcie_7x_0_0/pcie_gen1x1_sub_sys_pcie_7x_0_0/source/pcie_gen1x1_sub_sys_pcie_7x_0_0-PCIE_X0Y0.xdc id:2 order:EARLY scoped_inst:pcie_gen1x1_sub_sys_i/pcie_7x_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/sanjayr/projects/AC701/PCIe_gen2x8_PIO_test18/vivado_IPI_example_2/pcie_gen1x1_sub_sys_wrapper.xdc rfile:../../../../pcie_gen1x1_sub_sys_wrapper.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:/home/sanjayr/projects/AC701/PCIe_gen2x8_PIO_test18/vivado_IPI_example_2/project_X/project_X.srcs/sources_1/bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_auto_cc_1/pcie_gen1x1_sub_sys_auto_cc_1_clocks.xdc rfile:../../../project_X.srcs/sources_1/bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_auto_cc_1/pcie_gen1x1_sub_sys_auto_cc_1_clocks.xdc id:4 order:LATE scoped_inst:pcie_gen1x1_sub_sys_i/axi_mem_intercon/m03_couplers/auto_cc/inst} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB6 [get_ports {ddr3_dq[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA8 [get_ports {ddr3_dq[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y8 [get_ports {ddr3_dq[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB5 [get_ports {ddr3_dq[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA5 [get_ports {ddr3_dq[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y5 [get_ports {ddr3_dq[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y6 [get_ports {ddr3_dq[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y7 [get_ports {ddr3_dq[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF4 [get_ports {ddr3_dq[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF5 [get_ports {ddr3_dq[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF3 [get_ports {ddr3_dq[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE3 [get_ports {ddr3_dq[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD3 [get_ports {ddr3_dq[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC3 [get_ports {ddr3_dq[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB4 [get_ports {ddr3_dq[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA4 [get_ports {ddr3_dq[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC2 [get_ports {ddr3_dq[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB2 [get_ports {ddr3_dq[17]}]
set_property src_info {type:SCOPED_XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF2 [get_ports {ddr3_dq[18]}]
set_property src_info {type:SCOPED_XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE2 [get_ports {ddr3_dq[19]}]
set_property src_info {type:SCOPED_XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y1 [get_ports {ddr3_dq[20]}]
set_property src_info {type:SCOPED_XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y2 [get_ports {ddr3_dq[21]}]
set_property src_info {type:SCOPED_XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC1 [get_ports {ddr3_dq[22]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB1 [get_ports {ddr3_dq[23]}]
set_property src_info {type:SCOPED_XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y3 [get_ports {ddr3_dq[24]}]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W3 [get_ports {ddr3_dq[25]}]
set_property src_info {type:SCOPED_XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W6 [get_ports {ddr3_dq[26]}]
set_property src_info {type:SCOPED_XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V6 [get_ports {ddr3_dq[27]}]
set_property src_info {type:SCOPED_XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W4 [get_ports {ddr3_dq[28]}]
set_property src_info {type:SCOPED_XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports {ddr3_dq[29]}]
set_property src_info {type:SCOPED_XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W1 [get_ports {ddr3_dq[30]}]
set_property src_info {type:SCOPED_XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V1 [get_ports {ddr3_dq[31]}]
set_property src_info {type:SCOPED_XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G2 [get_ports {ddr3_dq[32]}]
set_property src_info {type:SCOPED_XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D1 [get_ports {ddr3_dq[33]}]
set_property src_info {type:SCOPED_XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E1 [get_ports {ddr3_dq[34]}]
set_property src_info {type:SCOPED_XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E2 [get_ports {ddr3_dq[35]}]
set_property src_info {type:SCOPED_XDC file:1 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F2 [get_ports {ddr3_dq[36]}]
set_property src_info {type:SCOPED_XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A2 [get_ports {ddr3_dq[37]}]
set_property src_info {type:SCOPED_XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A3 [get_ports {ddr3_dq[38]}]
set_property src_info {type:SCOPED_XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C2 [get_ports {ddr3_dq[39]}]
set_property src_info {type:SCOPED_XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C3 [get_ports {ddr3_dq[40]}]
set_property src_info {type:SCOPED_XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D3 [get_ports {ddr3_dq[41]}]
set_property src_info {type:SCOPED_XDC file:1 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A4 [get_ports {ddr3_dq[42]}]
set_property src_info {type:SCOPED_XDC file:1 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B4 [get_ports {ddr3_dq[43]}]
set_property src_info {type:SCOPED_XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C4 [get_ports {ddr3_dq[44]}]
set_property src_info {type:SCOPED_XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D4 [get_ports {ddr3_dq[45]}]
set_property src_info {type:SCOPED_XDC file:1 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D5 [get_ports {ddr3_dq[46]}]
set_property src_info {type:SCOPED_XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E5 [get_ports {ddr3_dq[47]}]
set_property src_info {type:SCOPED_XDC file:1 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F4 [get_ports {ddr3_dq[48]}]
set_property src_info {type:SCOPED_XDC file:1 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G4 [get_ports {ddr3_dq[49]}]
set_property src_info {type:SCOPED_XDC file:1 line:336 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K6 [get_ports {ddr3_dq[50]}]
set_property src_info {type:SCOPED_XDC file:1 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K7 [get_ports {ddr3_dq[51]}]
set_property src_info {type:SCOPED_XDC file:1 line:348 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K8 [get_ports {ddr3_dq[52]}]
set_property src_info {type:SCOPED_XDC file:1 line:354 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L8 [get_ports {ddr3_dq[53]}]
set_property src_info {type:SCOPED_XDC file:1 line:360 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J5 [get_ports {ddr3_dq[54]}]
set_property src_info {type:SCOPED_XDC file:1 line:366 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J6 [get_ports {ddr3_dq[55]}]
set_property src_info {type:SCOPED_XDC file:1 line:372 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G6 [get_ports {ddr3_dq[56]}]
set_property src_info {type:SCOPED_XDC file:1 line:378 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H6 [get_ports {ddr3_dq[57]}]
set_property src_info {type:SCOPED_XDC file:1 line:384 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F7 [get_ports {ddr3_dq[58]}]
set_property src_info {type:SCOPED_XDC file:1 line:390 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F8 [get_ports {ddr3_dq[59]}]
set_property src_info {type:SCOPED_XDC file:1 line:396 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G8 [get_ports {ddr3_dq[60]}]
set_property src_info {type:SCOPED_XDC file:1 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H8 [get_ports {ddr3_dq[61]}]
set_property src_info {type:SCOPED_XDC file:1 line:408 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D6 [get_ports {ddr3_dq[62]}]
set_property src_info {type:SCOPED_XDC file:1 line:414 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E6 [get_ports {ddr3_dq[63]}]
set_property src_info {type:SCOPED_XDC file:1 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N6 [get_ports {ddr3_addr[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:424 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L7 [get_ports {ddr3_addr[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L5 [get_ports {ddr3_addr[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:434 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N7 [get_ports {ddr3_addr[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K3 [get_ports {ddr3_addr[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H1 [get_ports {ddr3_addr[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M6 [get_ports {ddr3_addr[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:454 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K1 [get_ports {ddr3_addr[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:459 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M7 [get_ports {ddr3_addr[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:464 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K5 [get_ports {ddr3_addr[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L4 [get_ports {ddr3_addr[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:474 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J1 [get_ports {ddr3_addr[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:479 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J3 [get_ports {ddr3_addr[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:484 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M4 [get_ports {ddr3_addr[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:489 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H2 [get_ports {ddr3_ba[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:494 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M1 [get_ports {ddr3_ba[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:499 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N1 [get_ports {ddr3_ba[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:504 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P1 [get_ports {ddr3_ras_n}]
set_property src_info {type:SCOPED_XDC file:1 line:509 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T4 [get_ports {ddr3_cas_n}]
set_property src_info {type:SCOPED_XDC file:1 line:514 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R1 [get_ports {ddr3_we_n}]
set_property src_info {type:SCOPED_XDC file:1 line:519 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N8 [get_ports {ddr3_reset_n}]
set_property src_info {type:SCOPED_XDC file:1 line:524 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P4 [get_ports {ddr3_cke[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:529 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports {ddr3_odt[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:534 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T3 [get_ports {ddr3_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:539 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC6 [get_ports {ddr3_dm[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:544 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC4 [get_ports {ddr3_dm[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:549 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA3 [get_ports {ddr3_dm[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:554 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U7 [get_ports {ddr3_dm[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:559 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G1 [get_ports {ddr3_dm[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:564 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F3 [get_ports {ddr3_dm[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:569 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G5 [get_ports {ddr3_dm[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:574 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H9 [get_ports {ddr3_dm[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:578 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R3 [get_ports {sys_clk_p}]
set_property src_info {type:SCOPED_XDC file:1 line:582 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P3 [get_ports {sys_clk_n}]
set_property src_info {type:SCOPED_XDC file:1 line:588 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V8 [get_ports {ddr3_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:594 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W8 [get_ports {ddr3_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:600 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD5 [get_ports {ddr3_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:606 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE5 [get_ports {ddr3_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:612 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD1 [get_ports {ddr3_dqs_p[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:618 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE1 [get_ports {ddr3_dqs_n[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:624 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V3 [get_ports {ddr3_dqs_p[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:630 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V2 [get_ports {ddr3_dqs_n[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:636 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C1 [get_ports {ddr3_dqs_p[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:642 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B1 [get_ports {ddr3_dqs_n[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:648 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B5 [get_ports {ddr3_dqs_p[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:654 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A5 [get_ports {ddr3_dqs_n[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:660 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J4 [get_ports {ddr3_dqs_p[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:666 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H4 [get_ports {ddr3_dqs_n[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:672 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H7 [get_ports {ddr3_dqs_p[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:678 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G7 [get_ports {ddr3_dqs_n[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:683 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M2 [get_ports {ddr3_ck_p[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:688 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L2 [get_ports {ddr3_ck_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:692 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:693 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:694 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:695 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:696 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y11 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:697 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y10 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:698 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y9 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:699 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y15 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:700 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y14 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:701 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y13 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:702 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y12 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:704 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:705 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:706 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:707 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:711 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y15 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:712 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y14 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:713 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y13 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:714 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y12 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:718 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:719 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:720 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:721 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:722 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y11 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:723 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y10 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:724 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y9 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:725 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y15 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:726 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y14 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:727 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y13 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:728 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y12 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:730 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:731 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:732 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:733 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:734 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y15 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:735 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y14 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:736 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y13 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:737 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y12 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:739 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:1 line:740 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:1 line:741 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y3 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:1 line:743 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:1 line:744 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:1 line:745 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y3 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:1 line:747 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y93 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:748 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y81 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:749 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y69 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:750 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y57 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:751 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y193 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:752 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y181 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:753 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y169 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:754 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y157 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:756 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PLLE2_ADV_X1Y2 [get_cells -hier -filter {NAME =~ */u_ddr3_infrastructure/plle2_i}]
set_property src_info {type:SCOPED_XDC file:1 line:757 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC MMCME2_ADV_X1Y2 [get_cells -hier -filter {NAME =~ */u_ddr3_infrastructure/gen_mmcm.mmcm_i}]
set_property src_info {type:SCOPED_XDC file:1 line:781 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1*}] 20
set_property src_info {type:SCOPED_XDC file:1 line:782 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hier *rstdiv0_sync_r1_reg*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] -datapath_only 5
set_property src_info {type:SCOPED_XDC file:1 line:786 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *ddr3_infrastructure/rstdiv0_sync_r1_reg*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/xadc_supplied_temperature.rst_r1*}] 20
set_property src_info {type:SCOPED_XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTPE2_CHANNEL_X0Y7 [get_cells {inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gtp_channel.gtpe2_channel_i}]
set_property src_info {type:SCOPED_XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTPE2_COMMON_X0Y1 [get_cells {inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].pipe_quad.gt_common_enabled.gt_common_int.gt_common_i/qpll_wrapper_i/gtp_common.gtpe2_common_i}]
set_property src_info {type:SCOPED_XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PCIE_X0Y0 [get_cells inst/pcie_top_i/pcie_7x_i/pcie_block_i]
set_property src_info {type:SCOPED_XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X2Y46 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[3].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X1Y47 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[2].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X1Y46 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[1].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X1Y45 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[0].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X1Y44 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[0].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X1Y43 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[1].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X1Y42 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[2].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X1Y41 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[3].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/pclk_i1_bufgctrl.pclk_i1/S0}]
set_property src_info {type:SCOPED_XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/pclk_i1_bufgctrl.pclk_i1/S1}]
set_property src_info {type:XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M20 [get_ports pcie_sys_rst_n]
set_property src_info {type:XDC file:3 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X0Y2 [get_cells refclk_ibuf]
set_property src_info {type:XDC file:3 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -name TIG_AXI_ARESET_N -asynchronous  -group [get_clocks {inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/userclk1}] -group [get_clocks {u_pcie_gen1x1_sub_sys_mig_7series_0_0_mig/u_ddr3_infrastructure/clk_pll_i}]
set_property src_info {type:XDC file:3 line:12 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 labtools_ila_v3
set_property src_info {type:XDC file:3 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:3 line:22 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list pcie_gen1x1_sub_sys_i/pcie_7x_0_user_clk_out]]
set_property src_info {type:XDC file:3 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:3 line:24 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WSTRB[0]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WSTRB[1]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WSTRB[2]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WSTRB[3]}]]
set_property src_info {type:XDC file:3 line:25 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:3 line:27 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[0]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[1]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[2]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[3]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[4]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[5]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[6]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[7]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[8]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[9]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[10]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[11]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[12]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[13]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[14]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[15]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[16]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[17]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[18]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[19]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[20]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[21]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[22]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[23]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[24]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[25]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[26]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[27]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[28]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[29]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[30]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WDATA[31]}]]
set_property src_info {type:XDC file:3 line:28 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:3 line:30 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RRESP[0]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RRESP[1]}]]
set_property src_info {type:XDC file:3 line:31 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:3 line:33 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[0]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[1]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[2]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[3]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[4]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[5]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[6]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[7]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[8]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[9]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[10]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[11]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[12]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[13]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[14]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[15]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[16]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[17]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[18]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[19]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[20]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[21]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[22]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[23]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[24]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[25]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[26]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[27]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[28]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[29]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[30]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWADDR[31]}]]
set_property src_info {type:XDC file:3 line:34 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:3 line:36 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[0]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[1]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[2]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[3]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[4]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[5]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[6]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[7]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[8]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[9]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[10]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[11]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[12]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[13]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[14]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[15]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[16]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[17]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[18]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[19]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[20]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[21]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[22]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[23]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[24]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[25]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[26]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[27]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[28]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[29]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[30]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARADDR[31]}]]
set_property src_info {type:XDC file:3 line:37 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:3 line:39 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[0]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[1]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[2]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[3]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[4]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[5]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[6]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[7]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[8]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[9]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[10]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[11]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[12]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[13]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[14]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[15]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[16]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[17]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[18]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[19]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[20]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[21]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[22]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[23]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[24]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[25]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[26]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[27]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[28]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[29]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[30]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RDATA[31]}]]
set_property src_info {type:XDC file:3 line:40 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:3 line:42 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_BRESP[0]} {pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_BRESP[1]}]]
set_property src_info {type:XDC file:3 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:3 line:45 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARESETN]]
set_property src_info {type:XDC file:3 line:46 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:3 line:48 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARREADY]]
set_property src_info {type:XDC file:3 line:49 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:3 line:51 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_ARVALID]]
set_property src_info {type:XDC file:3 line:52 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:3 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWREADY]]
set_property src_info {type:XDC file:3 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_AWVALID]]
set_property src_info {type:XDC file:3 line:58 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:3 line:60 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_BREADY]]
set_property src_info {type:XDC file:3 line:61 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:3 line:63 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_BVALID]]
set_property src_info {type:XDC file:3 line:64 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:3 line:66 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RREADY]]
set_property src_info {type:XDC file:3 line:67 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:3 line:69 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_RVALID]]
set_property src_info {type:XDC file:3 line:70 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:3 line:72 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WREADY]]
set_property src_info {type:XDC file:3 line:73 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:3 line:75 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list pcie_gen1x1_sub_sys_i/pcie_axi_stream_to_axi_lite_bridge_0/inst/u_axiLite_debug/dbg_M_AXI_WVALID]]
set_property src_info {type:XDC file:3 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:SCOPED_XDC file:4 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_fanout -from [get_ports s_axi_aclk] -flat -endpoints_only] {IS_LEAF}] -to [filter [all_fanout -from [get_ports m_axi_aclk] -flat -only_cells] {IS_SEQUENTIAL}] -datapath_only [get_property PERIOD [get_clocks -of_objects [get_pins pcie_gen1x1_sub_sys_i/axi_mem_intercon/m03_couplers/auto_cc/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:4 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_fanout -from [get_ports m_axi_aclk] -flat -endpoints_only] {IS_LEAF}] -to [filter [all_fanout -from [get_ports s_axi_aclk] -flat -only_cells] {IS_SEQUENTIAL}] -datapath_only [get_property PERIOD [get_clocks -of_objects [get_pins pcie_gen1x1_sub_sys_i/axi_mem_intercon/m03_couplers/auto_cc/inst/m_axi_aclk]]]
