# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/sanjayr/projects/AC701/PCIe_gen2x8_PIO_test18/vivado_IPI_example_2/pcie_gen1x1_sub_sys_wrapper.xdc

# Block Designs: bd/pcie_gen1x1_sub_sys/pcie_gen1x1_sub_sys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys || ORIG_REF_NAME==pcie_gen1x1_sub_sys}]

# IP: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_axi_bram_ctrl_0_0/pcie_gen1x1_sub_sys_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_axi_bram_ctrl_0_0 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_axi_bram_ctrl_0_0}]

# IP: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_axi_gpio_LED_0/pcie_gen1x1_sub_sys_axi_gpio_LED_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_axi_gpio_LED_0 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_axi_gpio_LED_0}]

# IP: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_axi_gpio_sw_1/pcie_gen1x1_sub_sys_axi_gpio_sw_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_axi_gpio_sw_1 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_axi_gpio_sw_1}]

# IP: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_axi_mem_intercon_0/pcie_gen1x1_sub_sys_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_axi_mem_intercon_0 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_axi_mem_intercon_0}]

# IP: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_xbar_0/pcie_gen1x1_sub_sys_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_xbar_0 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_xbar_0}]

# IP: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_blk_mem_gen_0_0/pcie_gen1x1_sub_sys_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_blk_mem_gen_0_0 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_blk_mem_gen_0_0}]

# IP: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_mig_7series_0_0/pcie_gen1x1_sub_sys_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_mig_7series_0_0 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_mig_7series_0_0}]

# IP: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_pcie_7x_0_0/pcie_gen1x1_sub_sys_pcie_7x_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_pcie_7x_0_0 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_pcie_7x_0_0}]

# IP: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_pcie_axi_stream_to_axi_lite_bridge_0_0/pcie_gen1x1_sub_sys_pcie_axi_stream_to_axi_lite_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_pcie_axi_stream_to_axi_lite_bridge_0_0 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_pcie_axi_stream_to_axi_lite_bridge_0_0}]

# IP: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_rst_mig_7series_0_100M_0/pcie_gen1x1_sub_sys_rst_mig_7series_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_rst_mig_7series_0_100M_0}]

# IP: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_rst_pcie_sys_clk_100M_1/pcie_gen1x1_sub_sys_rst_pcie_sys_clk_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_rst_pcie_sys_clk_100M_1 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_rst_pcie_sys_clk_100M_1}]

# IP: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_auto_ds_5/pcie_gen1x1_sub_sys_auto_ds_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_auto_ds_5 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_auto_ds_5}]

# IP: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_auto_pc_2/pcie_gen1x1_sub_sys_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_auto_pc_2 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_auto_pc_2}]

# IP: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_auto_ds_6/pcie_gen1x1_sub_sys_auto_ds_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_auto_ds_6 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_auto_ds_6}]

# IP: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_auto_ds_7/pcie_gen1x1_sub_sys_auto_ds_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_auto_ds_7 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_auto_ds_7}]

# IP: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_auto_pc_3/pcie_gen1x1_sub_sys_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_auto_pc_3 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_auto_pc_3}]

# IP: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_auto_us_8/pcie_gen1x1_sub_sys_auto_us_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_auto_us_8 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_auto_us_8}]

# IP: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_auto_cc_1/pcie_gen1x1_sub_sys_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_auto_cc_1 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_auto_cc_1}]

# IP: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_auto_us_9/pcie_gen1x1_sub_sys_auto_us_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_auto_us_9 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_auto_us_9}]

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_axi_bram_ctrl_0_0/pcie_gen1x1_sub_sys_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_axi_gpio_LED_0/pcie_gen1x1_sub_sys_axi_gpio_LED_0_ooc.xdc

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_axi_gpio_LED_0/pcie_gen1x1_sub_sys_axi_gpio_LED_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_axi_gpio_LED_0 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_axi_gpio_LED_0}] {/U0 }]/U0 ]]

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_axi_gpio_LED_0/pcie_gen1x1_sub_sys_axi_gpio_LED_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_axi_gpio_LED_0 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_axi_gpio_LED_0}] {/U0 }]/U0 ]]

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_axi_gpio_sw_1/pcie_gen1x1_sub_sys_axi_gpio_sw_1_ooc.xdc

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_axi_gpio_sw_1/pcie_gen1x1_sub_sys_axi_gpio_sw_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_axi_gpio_sw_1 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_axi_gpio_sw_1}] {/U0 }]/U0 ]]

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_axi_gpio_sw_1/pcie_gen1x1_sub_sys_axi_gpio_sw_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_axi_gpio_sw_1 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_axi_gpio_sw_1}] {/U0 }]/U0 ]]

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_xbar_0/pcie_gen1x1_sub_sys_xbar_0_ooc.xdc

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_blk_mem_gen_0_0/pcie_gen1x1_sub_sys_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_mig_7series_0_0/pcie_gen1x1_sub_sys_mig_7series_0_0/user_design/constraints/pcie_gen1x1_sub_sys_mig_7series_0_0_ooc.xdc

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_mig_7series_0_0/pcie_gen1x1_sub_sys_mig_7series_0_0/user_design/constraints/pcie_gen1x1_sub_sys_mig_7series_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_mig_7series_0_0 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_mig_7series_0_0}]

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_mig_7series_0_0/pcie_gen1x1_sub_sys_mig_7series_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_mig_7series_0_0 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_mig_7series_0_0}]

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_pcie_7x_0_0/pcie_gen1x1_sub_sys_pcie_7x_0_0/source/pcie_gen1x1_sub_sys_pcie_7x_0_0-PCIE_X0Y0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_pcie_7x_0_0 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_pcie_7x_0_0}] {/inst }]/inst ]]

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_pcie_7x_0_0/synth/pcie_gen1x1_sub_sys_pcie_7x_0_0_ooc.xdc

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_rst_mig_7series_0_100M_0/pcie_gen1x1_sub_sys_rst_mig_7series_0_100M_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_rst_mig_7series_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_rst_mig_7series_0_100M_0/pcie_gen1x1_sub_sys_rst_mig_7series_0_100M_0_ooc.xdc

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_rst_mig_7series_0_100M_0/pcie_gen1x1_sub_sys_rst_mig_7series_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_rst_mig_7series_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_rst_pcie_sys_clk_100M_1/pcie_gen1x1_sub_sys_rst_pcie_sys_clk_100M_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_rst_pcie_sys_clk_100M_1 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_rst_pcie_sys_clk_100M_1}] {/U0 }]/U0 ]]

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_rst_pcie_sys_clk_100M_1/pcie_gen1x1_sub_sys_rst_pcie_sys_clk_100M_1_ooc.xdc

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_rst_pcie_sys_clk_100M_1/pcie_gen1x1_sub_sys_rst_pcie_sys_clk_100M_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_rst_pcie_sys_clk_100M_1 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_rst_pcie_sys_clk_100M_1}] {/U0 }]/U0 ]]

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_auto_ds_5/pcie_gen1x1_sub_sys_auto_ds_5_ooc.xdc

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_auto_ds_5/pcie_gen1x1_sub_sys_auto_ds_5_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_auto_ds_5 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_auto_ds_5}] {/inst }]/inst ]]

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_auto_pc_2/pcie_gen1x1_sub_sys_auto_pc_2_ooc.xdc

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_auto_ds_6/pcie_gen1x1_sub_sys_auto_ds_6_ooc.xdc

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_auto_ds_6/pcie_gen1x1_sub_sys_auto_ds_6_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_auto_ds_6 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_auto_ds_6}] {/inst }]/inst ]]

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_auto_ds_7/pcie_gen1x1_sub_sys_auto_ds_7_ooc.xdc

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_auto_ds_7/pcie_gen1x1_sub_sys_auto_ds_7_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_auto_ds_7 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_auto_ds_7}] {/inst }]/inst ]]

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_auto_pc_3/pcie_gen1x1_sub_sys_auto_pc_3_ooc.xdc

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_auto_us_8/pcie_gen1x1_sub_sys_auto_us_8_ooc.xdc

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_auto_us_8/pcie_gen1x1_sub_sys_auto_us_8_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_auto_us_8 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_auto_us_8}] {/inst }]/inst ]]

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_auto_cc_1/pcie_gen1x1_sub_sys_auto_cc_1_ooc.xdc

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_auto_cc_1/pcie_gen1x1_sub_sys_auto_cc_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_auto_cc_1 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_auto_cc_1}] {/inst }]/inst ]]

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_auto_us_9/pcie_gen1x1_sub_sys_auto_us_9_ooc.xdc

# XDC: bd/pcie_gen1x1_sub_sys/ip/pcie_gen1x1_sub_sys_auto_us_9/pcie_gen1x1_sub_sys_auto_us_9_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_gen1x1_sub_sys_auto_us_9 || ORIG_REF_NAME==pcie_gen1x1_sub_sys_auto_us_9}] {/inst }]/inst ]]

# XDC: bd/pcie_gen1x1_sub_sys/pcie_gen1x1_sub_sys_ooc.xdc
